//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sw.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextConocimiento : DbContext
    {
        public ContextConocimiento()
            : base("name=ContextConocimiento")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaTest> CategoriaTest { get; set; }
        public virtual DbSet<PreguntaTest> PreguntaTest { get; set; }
        public virtual DbSet<RespuestaTest> RespuestaTest { get; set; }
    }
}
