//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntaTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreguntaTest()
        {
            this.RespuestaTest = new HashSet<RespuestaTest>();
        }
    
        public int PreguntaTestId { get; set; }
        public int CategoriaTestId { get; set; }
        public string Pregunta { get; set; }
        public bool Estado { get; set; }
    
        public virtual CategoriaTest CategoriaTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestaTest> RespuestaTest { get; set; }
    }
}
